language: android

sudo: false

android:
  components:
  - build-tools-24.0.2
  - android-23
  - extra-android-m2repository
  - extra-android-support

script:
  - "./gradlew assembleRelease"

  gem install travis
